// Agency nav links
export default {
   earmFaevaaCash: [
      {
         "menu_title": "Offer Walls",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/offer-walls",
         "new_item": false,
         "child_routes": null,
      },
      {
         "menu_title": "Survey Walls",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/survey-walls",
         "new_item": false,
         "child_routes": null,
      },
      {
         "menu_title": "Videos",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/videos",
         "new_item": false,
         "child_routes": null,
         "custom": true,
      },
      {
         "menu_title": "Games",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/games",
         "new_item": false,
         "child_routes": null,
      },
      {
         "menu_title": "Search the Web",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/search-web",
         "new_item": false,
         "child_routes": null,
      },
      {
         "menu_title": "Shopping",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/shopping",
         "new_item": false,
         "child_routes": null,
      },
      {
         "menu_title": "EZ Cash Offers",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/ez-cach-offers",
         "new_item": false,
         "child_routes": null,
      },
   ],
   faevaaRewards: [
      {
         "menu_title": "Reward Locker",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/reward-locker",
         "new_item": false,
         "child_routes": null,
      },
      {
         "menu_title": "Redemption History",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/redemption-history",
         "new_item": false,
         "child_routes": null,
      },
      {
         "menu_title": "Testimonials",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/testimonials",
         "new_item": false,
         "child_routes": null,
         "custom": true,
      },
      {
         "menu_title": "Leave Testimonial",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/leave-testimonial",
         "new_item": false,
         "child_routes": null,
      },
   ],
   testYourLuck: [
      {
         "menu_title": "Faevaa Lottery",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/faevaa-lottery",
         "new_item": false,
         "child_routes": null,
      },
      {
         "menu_title": "Raffles",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/raffles",
         "new_item": false,
         "child_routes": null,
      },
      {
         "menu_title": "Member Contests",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/member-contests",
         "new_item": false,
         "child_routes": null,
         "custom": true,
      },
      {
         "menu_title": "My Wins",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/my-wins",
         "new_item": false,
         "child_routes": null,
      },
   ],
   refferalZone: [
      {
         "menu_title": "Refer Friends",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/refer-friends",
         "new_item": false,
         "child_routes": null,
      },
      {
         "menu_title": "My Referral History",
         "menu_icon": "zmdi zmdi-crop",
         "path": "/my-referral-history",
         "new_item": false,
         "child_routes": null,
      },
   ],
}
