export const testimonials = [
    {
        id:1,
        image:require('Assets/img/user-2.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:2,
        image:require('Assets/img/user-3.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:3,
        image:require('Assets/img/user-1.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:4,
        image:require('Assets/img/user-4.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:5,
        image:require('Assets/img/user-7.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:6,
        image:require('Assets/img/user-4.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:7,
        image:require('Assets/img/user-5.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:8,
        image:require('Assets/img/user-2.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:9,
        image:require('Assets/img/user-8.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:10,
        image:require('Assets/img/user-7.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:11,
        image:require('Assets/img/user-6.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:12,
        image:require('Assets/img/user-5.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:13,
        image:require('Assets/img/user-3.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        rating:5,
        email:'info@email.com',
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:14,
        image:require('Assets/img/user-1.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:15,
        image:require('Assets/img/user-4.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:16,
        image:require('Assets/img/user-2.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:17,
        image:require('Assets/img/user-6.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:18,
        image:require('Assets/img/user-5.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:19,
        image:require('Assets/img/user-2.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:20,
        image:require('Assets/img/user-5.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:21,
        image:require('Assets/img/user-4.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        rating:5,
        email:'info@email.com',
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    },
    {
        id:22,
        image:require('Assets/img/user-2.jpg'),
        firstName:'Kate',
        lastName:'Louise',
        email:'info@email.com',
        rating:5,
        date:'2020-04-19',
        feedBack:'Duis non leo nec ligula sodales interdum, ante leo rhoncus est, id laoreet neque libero in velit. Phasellus bibendum lorem at velit venenatis consequat eget eget sapien. Donec vel turpis lacinia, varius massa ac, cursus neque. Cras porta, quam ut facilisis pharetra, ante nisl imperdiet odio, sed vestibulum dui mauris non magna.',
    }
]